UX improvements
aws/aws-sam-cli-pipeline-init-templates pull request #19
Opened 2021-06-23 23:36 UTC by elbayaaa

*Issue #, if available:*
N/A

*Description of changes:*
Some UX improvements

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-06-23 23:44 UTC, aahung approved these changes

2021-06-24 06:38 UTC, hoffa requested changes

2021-06-24 06:38 UTC, hoffa commented on GitHub-Actions/two-environment-pipeline-template/questions.json
> +    "question": "\nThis template configures a pipeline that deploys a serverless application to a testing and a production environments.\n",
```suggestion
    "question": "\nThis template configures a pipeline that deploys a serverless application to a testing and a production environment.\n",
```

2021-06-24 06:38 UTC, hoffa commented on Gitlab/two-environment-pipeline-template/questions.json
> +    "question": "\nThis template configures a pipeline that deploys a serverless application to a testing and a production environments.\n",
```suggestion
    "question": "\nThis template configures a pipeline that deploys a serverless application to a testing and a production environment.\n",
```

2021-06-24 06:38 UTC, hoffa commented on GitHub-Actions/two-environment-pipeline-template/questions.json
>      "question": "What is the GitHub Secret name for pipeline user account access key id?",
```suggestion
    "question": "What is the GitHub secret name for pipeline user account access key ID?",
```

2021-06-24 06:38 UTC, hoffa commented on Gitlab/two-environment-pipeline-template/questions.json
>      "question": "What is the git branch used for production deployments?",
```suggestion
    "question": "What is the Git branch used for production deployments?",
```

2021-06-24 06:38 UTC, hoffa commented on Gitlab/two-environment-pipeline-template/{{cookiecutter.outputDir}}/.gitlab-ci.yml
> +# uncomment and modify the following step for running the integration-tests
```suggestion
# Uncomment and modify the following stage for integration tests
```

2021-06-24 06:38 UTC, hoffa commented on Jenkins/two-environment-pipeline-template/questions.json
> +    "question": "\nThis template configures a pipeline that deploys a serverless application to a testing and a production environments.\n",
```suggestion
    "question": "\nThis template configures a pipeline that deploys a serverless application to a testing and a production environment.\n",
```

2021-06-24 06:40 UTC, hoffa commented on GitHub-Actions/two-environment-pipeline-template/questions.json
>      "question": "What is the GitHub Secret name for pipeline user account access key id?",
Actually this applies to all instances:

- Should be "GitHub secrets"; it's not used as a proper noun.
- ID should be all caps.
- Git should be capitalized (not "git").

2021-06-25 00:08 UTC, xazhao approved these changes
LGTM!

2021-06-25 00:10 UTC, hoffa approved these changes
LGTM; we should still do the following before release:

- Should be "GitHub secret"; it's not used as a proper noun.
- ID should be all caps.
- Git should be capitalized (not "git").

2021-06-25 05:55 UTC, merged