Add README title/description and cleanup whitespace
aws/aws-sam-cli-pipeline-init-templates pull request #38
Opened 2021-07-22 15:57 UTC by 1davidmichael

## Description of changes:

This PR contains some quality of life updates to the project that I think it will make it easier to use and for contributions in the future.

### README Update
This change adds a more complete README.md with some details on what the repo is for and how it can be utilized. It was based off the [aws-sam-cli](https://github.com/aws/aws-sam-cli) and [aws-sam-cli-app-templates](https://github.com/aws/aws-sam-cli-app-templates) repos.

### Whitespace Cleanup
I also have added a [pre-commit config file](https://pre-commit.com/) which I used to cleanup various whitespace within the templates. The use of pre-commit is optional but the hooks are nice to have. I can remove it if preferred.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-07-26 22:37 UTC, c2tarun approved these changes
Thanks a lot for this commit. Really appreciate it.

2021-07-26 22:40 UTC, aahung requested changes
Thanks for this PR! Some minor change requests

2021-07-26 22:40 UTC, aahung commented on README.md
> +This repository containers the pipeline init templates used in the AWS SAM CLI for `sam pipeline` calls.
```suggestion
This repository contains the pipeline init templates used in the AWS SAM CLI for `sam pipeline` commands.
```

2021-07-27 21:30 UTC, aahung approved these changes

2021-07-27 21:32 UTC, merged