fix: Bump github action versions
aws/aws-sam-cli-pipeline-init-templates pull request #73
Opened 2024-10-08 07:19 UTC by aphilippartd

*Issue #, if available:*

*Description of changes:*
Bumped version of Github Actions actions used in the `Github-Actions/two-stage-pipeline-template` that were using deprecated versions.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-08 17:11 UTC, dkphm approved these changes

2024-10-08 17:25 UTC, hawflau approved these changes

2024-10-08 17:28 UTC, hawflau requested changes
Thanks for your contributions. LGTM but tests are breaking. Can you please update these two files?
- https://github.com/aws/aws-sam-cli-pipeline-init-templates/blob/main/tests/testfile_github/expected_iam.yaml
- https://github.com/aws/aws-sam-cli-pipeline-init-templates/blob/main/tests/testfile_github/expected_oidc.yaml

2024-10-09 06:36 UTC, aphilippartd commented
Done @hawflau thanks

2024-10-09 14:48 UTC, hawflau approved these changes
LGTM!

2024-10-09 14:48 UTC, merged